/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import beans.Student;
import java.io.FileNotFoundException;
import model.EstModel;

import javax.swing.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sec.Secuencial;

/**
 *
 * @author jf_me
 */
public class AddFrame extends javax.swing.JInternalFrame {
    private EstModel mod;
    private Secuencial secuencial;
    private DefaultComboBoxModel depmod;
    private DefaultComboBoxModel munmod;
    /**
     * Creates new form AddFrame
     */
    public AddFrame() {
        initComponents();
    }

    public EstModel getMod() {
        return mod;
    }

    public void setMod(EstModel mod) {
        this.mod = mod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        addbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        surnametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        carnettxt = new javax.swing.JTextField();
        carreercmb = new javax.swing.JComboBox<>();
        citycmb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        deptcmb = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Añadir estudiante");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        addbtn.setText("Añadir");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn);

        savebtn.setText("Guardar y Cerrar");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        jPanel1.add(savebtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Edad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 5, 30);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Carnet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Carrera");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Ciudad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 25);
        jPanel2.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.weightx = 0.001;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(nametxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.weightx = 0.001;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(surnametxt, gridBagConstraints);

        agetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agetxtKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.weightx = 0.001;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(agetxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.weightx = 0.001;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(carnettxt, gridBagConstraints);

        carreercmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ing. Sistemas", "Ing. Industrial", "Ing. Mecánica", "Ing. Civil", "Ing. Agricola" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.weightx = 0.001;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(carreercmb, gridBagConstraints);

        citycmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Managua", "Tipitapa", "León", "Masaya", "Chinandega", "Matagalpa", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.weightx = 0.001;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(citycmb, gridBagConstraints);

        jLabel7.setText("Departamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel7, gridBagConstraints);

        deptcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deptcmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deptcmbItemStateChanged(evt);
            }
        });
        deptcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptcmbActionPerformed(evt);
            }
        });
        deptcmb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                deptcmbPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(deptcmb, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 410, 308);
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String name=nametxt.getText();
        String surname=surnametxt.getText();
        int age=Integer.parseInt(agetxt.getText());
        String Carnet=carnettxt.getText();
        String carreer= (String) carreercmb.getSelectedItem();
        String dept=(String) deptcmb.getSelectedItem();
        String city= (String) citycmb.getSelectedItem();
        Student s=new Student(0,name,surname,Carnet,carreer,city,dept, age);
        if(localadd(s)){
            JOptionPane.showMessageDialog(this, "Se ha agregado correctamente", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "No se ha podido agregar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void agetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agetxtKeyTyped
        char key=evt.getKeyChar();
        if(!Character.isDigit(key)){
            evt.consume();
            agetxt.setBorder(
                    new javax.swing.border.LineBorder(
                            new java.awt.Color(131, 2, 0),
                            1, true));
        }else{
            agetxt.setBorder(null);
        }
    }//GEN-LAST:event_agetxtKeyTyped

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        String name=nametxt.getText();
        String surname=surnametxt.getText();
        int age=Integer.parseInt(agetxt.getText());
        String Carnet=carnettxt.getText();
        String carreer= (String) carreercmb.getSelectedItem();
        String dept=(String) deptcmb.getSelectedItem();
        String city= (String) citycmb.getSelectedItem();
        Student s=new Student(0,name,surname,Carnet,carreer,city,dept, age);
        if(localadd(s)){
            JOptionPane.showMessageDialog(this, "Se ha agregado correctamente", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "No se ha podido agregar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_savebtnActionPerformed

    private void deptcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptcmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptcmbActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            secuencial=new Secuencial("dept.csv");
            String[] depts=secuencial.readText().split(",");
            String[] cop=new String[depts.length+1];
            System.arraycopy(depts, 0, cop,1, depts.length);
            cop[0]="Seleccione una opcion";
            depmod=new DefaultComboBoxModel(cop);
            munmod=new DefaultComboBoxModel(new String[0]);
            deptcmb.setModel(depmod);
            citycmb.setModel(munmod);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void deptcmbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_deptcmbPropertyChange
        
    }//GEN-LAST:event_deptcmbPropertyChange

    private void deptcmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deptcmbItemStateChanged
        int index=deptcmb.getSelectedIndex();
        if(index==0){
            munmod=new DefaultComboBoxModel(new String[0]);
            citycmb.setModel(munmod);
            return;
        }
        try {
            secuencial=new Secuencial("munip.csv");
            String[] munips=secuencial.readText().split("\n");
            String[] mun=munips[index-1].split(",");
            munmod=new DefaultComboBoxModel(mun);
            citycmb.setModel(munmod);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_deptcmbItemStateChanged

    private boolean localadd(Student s){
        try {
            mod.add(s);
            return true;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField carnettxt;
    private javax.swing.JComboBox<String> carreercmb;
    private javax.swing.JComboBox<String> citycmb;
    private javax.swing.JComboBox<String> deptcmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField surnametxt;
    // End of variables declaration//GEN-END:variables
}
